version: '3'

services:
  dev:
    image: mcr.microsoft.com/devcontainers/base:bookworm
    container_name: inf339t3    
    volumes:
      - .:/workspaces/inf339t3:cached
    command: sleep infinity
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    networks:
      - devnet

  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - devnet

  kafka:
    image: confluentinc/cp-kafka:7.2.1
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - devnet

networks:
  devnet: